// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	INVITE_STATIC: "lobsterchess";
	LOBBY: DurableObjectNamespace<import("./src/index").LobbyDO>;
	GAME: DurableObjectNamespace<import("./src/index").GameDO>;
	RATINGS: DurableObjectNamespace<import("./src/index").RatingsDO>;
	CHALLENGES: DurableObjectNamespace<import("./src/index").ChallengesDO>;
}
